blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/BigThunderSR/node-red-contrib-onstar2/discussions
    about: Use discussions for general questions or help with the project.
