# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package - Publish to NPM Registry

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22.x
      - run: npm ci
      #- run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - id: publish
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}        
      - if: steps.publish.outputs.type != 'none'
        name: Update Node-Red flow-library
        uses: BigThunderSR/update-package-node-red-flow-library-action@v1.3.15
        continue-on-error: true
        with:
          package-name: 'node-red-contrib-onstar2'
          delay-run-ms: 10000
