# This workflow executes several linters on changed files based on languages used in your code base whenever
# you push a code or open a pull request.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/github/super-linter
name: Lint Code Base

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_run:
    workflows: ["CodeQL"]    
    types: [completed]

#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref }}
#  cancel-in-progress: false

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      #- name: Install @babel dependencies
      #  run: npm install @babel/eslint-plugin@latest --save-dev
      - name: Install Dependencies
        run: npm install --include=dev    
      
      - name: Lint Code Base
        #uses: github/super-linter@v6
        uses: github/super-linter@latest
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #FILTER_REGEX_EXCLUDE: (onstar.js|onstar.html|vehicle.js)
          LINTER_RULES_PATH: /          
          #JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.yml #Prior to ESLint V9
          #JAVASCRIPT_ES_CONFIG_FILE: eslint.config.cjs
          VALIDATE_JAVASCRIPT_ES: true
          ESLINT_USE_FLAT_CONFIG: false
