name: Test - Update Node-Red flow-library
on:
 workflow_dispatch:
 
jobs:
  update-flow-library:
    runs-on: ubuntu-latest
    steps: 
     - uses: BigThunderSR/update-package-node-red-flow-library-action@v1.3.15    
       with:         
         package-name: 'node-red-contrib-onstar2'
         #delay-run-ms: 10000
